// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yulpvhbaosuwnxdikhdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1bHB2aGJhb3N1d254ZGlraGRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczODAwMDYsImV4cCI6MjA3Mjk1NjAwNn0._4gVTzAMxjekHbYQmSsS8L_L0bXQYAGi5RSOmbruNRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});